a <- read.csv("household_power_consumption.txt",sep=";")
a$Date <- as.Date(a$Date,format="%d/%m/%Y")
b <- subset(a, Date == "2007-02-01" | Date == "2007-02-02")
b$DateTime <- strptime(paste(b$Date,b$Time), format="%Y-%m-%d %H:%M:%S")
b[,7] <- as.numeric(as.character(b[,7]))
b[,8] <- as.numeric(as.character(b[,8]))
b[,9] <- as.numeric(as.character(b[,9]))
png(filename="plot3.png", width=480, height=480)
plot(b$DateTime, b[,7],type="n", xlab="", ylab="Energy sub metering")
lines(b$DateTime, b[,7])
lines(b$DateTime, b[,8], col="red")
lines(b$DateTime, b[,9], col="blue")
legend("topright", names(b)[7:9], lty=1, col=c("black","red","blue"))
dev.off()