a <- read.csv("household_power_consumption.txt",sep=";")
a$Date <- as.Date(a$Date,format="%d/%m/%Y")
b <- subset(a, Date == "2007-02-01" | Date == "2007-02-02")
b[,3] <- as.numeric(as.character(b[,3]))
b[,4] <- as.numeric(as.character(b[,4]))
b[,5] <- as.numeric(as.character(b[,5]))
b[,7] <- as.numeric(as.character(b[,7]))
b[,8] <- as.numeric(as.character(b[,8]))
b[,9] <- as.numeric(as.character(b[,9]))
b$DateTime <- strptime(paste(b$Date,b$Time), format="%Y-%m-%d %H:%M:%S")
png(filename="plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(b$DateTime,b[,3], type="n", xlab="", ylab="Global Active Power")
lines(b$DateTime,b[,3])
plot(b$DateTime,b[,5], type="n", xlab="datetime", ylab="Voltage")
lines(b$DateTime,b[,5])
plot(b$DateTime, b[,7],type="n", xlab="", ylab="Energy sub metering")
lines(b$DateTime, b[,7])
lines(b$DateTime, b[,8], col="red")
lines(b$DateTime, b[,9], col="blue")
legend("topright", names(b)[7:9], lty=1, col=c("black","red","blue"), bty="n")
plot(b$DateTime,b[,4], type="n", xlab="datetime", ylab="Global_reactive_power")
lines(b$DateTime,b[,4])
dev.off()